name: car_learning_app
description: A Flutter app to help users learn about cars and their specifications.
publish_to: "none"
version: 1.0.2+4   #change in android/app/build.gradle.kts

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^6.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  tutorial_coach_mark: ^1.3.0
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  google_sign_in: ^7.2.0
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.0+1
  cloud_firestore: ^6.0.3
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  dio: ^5.4.0
  url_launcher: ^6.1.11
  easy_localization: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/cars.csv
    - assets/home/
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/translations/